@devHost = http://localhost:8080
@prodHost = https://sheets-on-run-fywh4w3uiq-du.a.run.app
@host = {{devHost}}
# @host = {{prodHost}}
@sheet=1uIV7rfb3TX_bxmDaAonb-8xaDX0NrWKw8S4b-V96MR4
@tab=시트1

### get root path
GET {{host}}/ HTTP/1.1


### get sheet row
GET {{host}}/data
  ?sheet={{sheet}}
  &tab={{tab}}
  &key=column4
  &value=column3

### get sheet row with id
GET {{host}}/data
  ?sheet={{sheet}}
  &tab={{tab}}
  &row=10

### put sheet row with id
PUT {{host}}/data
  ?sheet={{sheet}}
  &tab={{tab}}
  &row=5
content-type: application/json

{
  "column5": "zzz111"
}

### put sheet row with key, value
PUT {{host}}/data
  ?sheet={{sheet}}
  &tab={{tab}}
  &key=key
  &value=test
content-type: application/json

{
  "column2": "3333"
}

### post sheet row
POST {{host}}/data
  ?sheet={{sheet}}
  &tab={{tab}}
content-type: application/json

{
  "key": "test",
  "column2": "columnddd1",
  "column5": "columndddddssfs3"
}
